branch-defaults:
  automate:
    environment: concierge-env
    group_suffix: null
environment-defaults:
  concierge-env:
    branch: null
    repository: null
global:
  application_name: concierge-service
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
